[package]
name = "random-number"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { workspace = true, features = ["guest"] }
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
serde = { workspace = true } 